spring:
  application:
    name: CallAutomation_OutboundCalling

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        same-site: none
        secure: false
  compression:
    enabled: true
  http2:
    enabled: true

acs:
  connectionstring: ""
  callbackUriHost: ""
  acsPhoneNumber: ""
  targetphonenumber: ""
  cognitiveServiceEndpoint: ""
  targetTeamsUserId: <(OPTIONAL) YOUR TARGET TEAMS USER ID ex. "ab01bc12-d457-4995-a27b-c405ecfe4870">
